GET http://localhost:5215/todos

### 
GET http://localhost:5215/todos/2

###
POST http://localhost:5215/todos
Content-Type: application/json

{
    "id": 1,
    "name": "Mighty Task",
    "dueDate": "2029-12-31T23:59:59.999Z",
    "isCompleted": false
}

###
DELETE http://localhost:5215/todos/2

###
GET http://localhost:5215/tasks/1